export const materiaPrima = [
    {
        NroPedido: 1,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 2,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 3,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 4,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 5,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 6,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 7,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 8,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 9,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 10,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Pendientes",
    },
    {
        NroPedido: 11,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Penidente",
    },
    {
        NroPedido: 12,
        Fecha: "08/06/2022",
        Cliente: 'Juan Lopez',
        Producto: 'Botella',
        Cantidad: 30,
        Estado: "Penidente",
    },

];







/*
    id: 1,
    Categoria: 'Pet',
    cantidad: 10,
    Peso: 30,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 2,
    Categoria: 'HDPE',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023"
},
{
    id: 3,
    Categoria: 'PVC',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 4,
    Categoria: 'LDPE',
    cantidad: 10,
    Peso: 5,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 5,
    Categoria: 'PS',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},
{
    id: 6,
    Categoria: 'O',
    cantidad: 10,
    Peso: 3,
    Proveedor: "Ricardo",
    Precio: 34,
    Fecha: "10-05-2023",
},

];*/

