export { default as Clientes } from "./clientes/Clientes";
export { default as Search } from "./search/Search";
export { default as Empleado } from "./empleado/Empleado";
export { default as Recuadro } from "./recuadro/Recuadro";
export { default as ListaClientes } from "./lista/ListaClientes";
export { default as ListaProveedores } from "./lista/ListaProveedores";
export { default as Navbar33 } from "./navbar/Navbar33";
export { default as Proveedores1 } from "./proveedores/Proveedores";
export { default as IngrosoMateriaP } from "./produccion/materiaPrima/IngresoMP";
export { default as IngrosoProducto } from "./produccion/producto/IngresoProduct"
export { default as MateriaPrima } from "./produccion/materiaPrima/MateriaPrima0"
export { default as Productos } from "./produccion/producto/Producto";
export { default as HomeAdm } from "./homeAdm/home"
export { default as ListaUsuario } from "./usuarioss/ListaUsuario"
export { default as NavHome } from "./navbar/navbarHome"
export { default as Pedido } from "./produccion/pedidos/Usuarioo"
export { default as Modale } from "./modale/Modale";
export { default as Navbar2 } from "./navbar/Navbar2";
export { default as Navbar1 } from "./navbar/Navbar1";
export { default as Navbar } from "./navbar/Navbar";
export { default as Login } from "./login/Login";
export { default as Login1 } from "./login/Login1";
export { default as BotonD } from "./botondesplegable/BotonD";
export { default as Usuarioo1 } from "./produccion/pedidos/Usuarioo"

